### PR TITLE
Changed username format to Username@ClusterName

### LINKED ISSUE #42: Make user config key in kubeconfig configurable
We manage multiple kubernetes clusters and use gangway for onboarding.

The default template sets the username to be the email in [commandline.tmpl](https://github.com/heptiolabs/gangway/blob/70325f522fe2948149a87c1c825986424343157a/templates/commandline.tmpl#L63). This is overwriting the user once we use another instance of gangway to generate a config for a second cluster.

The option to, for example, set it to  `{{ .ClusterName }}-{{ .Email }}` without forking the project would be great.

### PR DESCRIPTION
**Pull request by hrzbrg**
In order to use Gangway with more than one customer cluster, the user in the kubeconfig file must be unique. This change sets the user for kubeconfig to Username@ClusterName.
Fixes #42

### CODE REVIEW

**Comment by stevesloka** [comment]
Hey @hrzbrg could you rebase this? Thanks!

**Comment by hrzbrg** [comment]
✅

**Comment by stevesloka** [comment]
hey @hrzbrg, seems like the sign-off bot is unhappy now. Could you check to make sure you have the commit signed? Thanks!

**Comment by stevesloka** [comment]
LGTM, thanks @hrzbrg!

**Pull request merged**
