### PR TITLE
fix: Commands from commandline template fail when cluster name or credential name contain spaces

### PR DESCRIPTION
**Pull request by nickperry**
Fixes https://github.com/heptiolabs/gangway/issues/131

### CODE REVIEW

**Comment by johnharris85** [comment]
Thanks for the PR @nickperry, can you sign your commit please? 

Test failure doesn't look related so hopefully it's a flake and works when kicked off again, if not we can take a look at it.

**Comment by nickperry** [comment]
Signed :)

**Comment by nickperry** [comment]
Hi @johnharris85 - can we get this merged?

**Comment by danielsand** [comment]
@johnharris85 hey, we really would love to see this getting merged. Any way to help and speed up the process ?

**Comment by johnharris85** [comment]
ping @alexbrand / @stevesloka

**Comment by danielsand** [comment]
any way to speed up the merge of this fix getting to master ?
@alexbrand / @stevesloka

**Comment by danielsand** [comment]
@stevesloka thanks for the merge - following question:
When will be the next official release ? =]

**Comment by stevesloka** [comment]
Hey, @danielsand I think we'll have one soon. There are a couple other issues that we want to get fixed up. There's also a small bit of work to update the release pipeline.

**Comment by zanloy** [comment]
Still no new release? This fix would be great in an official release and docker image.

**Pull request merged**
